"""Initial

Revision ID: fe5b144aceec
Revises: 
Create Date: 2025-12-12 00:28:35.901674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5b144aceec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('image_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('is_deleted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('deleted_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        # создаём индекс (имя формируется через batch_op.f(...))
        batch_op.create_index(batch_op.f('ix_recipes_is_deleted'), ['is_deleted'], unique=False)
        # создаём внешние ключи с явными именами
        batch_op.create_foreign_key('fk_recipes_category_id_categories', 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key('fk_recipes_author_id_users', 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        # удаляем внешние ключи по именам, которые мы задали в upgrade
        batch_op.drop_constraint('fk_recipes_category_id_categories', type_='foreignkey')
        batch_op.drop_constraint('fk_recipes_author_id_users', type_='foreignkey')
        # удаляем индекс (имя такое же, как было создано)
        batch_op.drop_index(batch_op.f('ix_recipes_is_deleted'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('author_id')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
